---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: blitz-secrets
  namespace: blitz
spec:
  encryptedData:
    DATABASE_URL: AQAnOvMIWNGXXxZUbcLpge7ZBK3Y+XwB7W4Kp0//6ESAptzKc/MPZe6IMqza/xq3/qD+X5UB5T5L8I96K4Q9oswBq2NFlH/3aKeS/vz9X++5IKCKdi3gZkCkr13h4chR9ACKDKhPPFhli3kJwVqyR5kDCKrAPiZUb7Be92I3tLw8eQofRyjkTygeNts2NPDARcigsfIY+rdBOKyKEwtgUURtG6RTHWQvz4BelxwXKS7juM+QBPxLL50s/WgIj+OF1ttx7qtXGVjZA/O1pTA9SAMDI62EOvin5o3HN437Vxv+3UAhqO0Rr5REfsNTxell1oqIDBwVAupWleLwjk/BXnXKVhe7Hy9Jxw4r0ng7xrKKh0WaBeEejNRdEYUsIRHeeg3JOARSLLJDlccN7ZjcOpvbDp6zxmb2wwgN9wu7qo7ZofmWzOv4qjqqwGPJ
    ETH_HOT_WALLET_KEY: AQATp7xmIcig75VkH7eAn42Vsd24+ztZPfbavjI1EohK6UXhNyLLijTLeZ3PVBvnJoAb546YK01cqiWjNoeOMJEFhwrtmJRKt7GyDMVGnpGKEbs0XURHS7x7m7ANeT0eBEZfEVZhBssqERd7hAZv21XqsbDkZEGYW9npYNe+5yq91rdmE8nERYIQ341TQkbdSU/fyDb/jusy/iFBtYzi75EFAiy52h0ihR/47HJ9Gub+1DPsqmOMOy2ly00yyPpubsS7rXl4hQWGP30DYK3oW04CAGFIEp97p/f3y1RPm4eib/ZsKIcLolVMbrtIVKaq5lZ9ru9LsTcTqu6F7olb8zYAeH8gPPvNZQ34ySeZakMh8w==
    JWT_SECRET: AQBbZFjFOBaDeS5q68z+W0o4j/wAW+nvbo5a3dmix6q5NNzLkpBGX+B7trc10FFaPWET9zeyG0HTOvKxyW41QT8nTcbrtWu2TCnq4kqzUVbVFjE+GOukAGgyhGf96pMLkyLo9fp6w1zFZEadsJahIswQmq2Hr6Fe+UQhGP4g5rPDR20g5vNszo/07AnZ+EfqDU1zjyyg9yY210w23nA0sG0xKwVvTP6rTJoU1kqyG6AjnShY4mGToxtWADZfKhZq8jHlnfXk/1mDQEHPlwr6Kq3SWzG81GpaRhfmAMkTZ5mKsS7i733JiBayQvz+LoAnTrnQEkyMQ5lR+rPfyxwc1T4ttEUK2IUGKC+F8ILg8qI4atW9C8t7SrP6+TXpCzkorUlAGyoCTck4tqs061XUI6I=
    SMTP_PASS: AQAKTwaPVAoBgde2lyiEGfzHYAi37Gx+DeZPPnWHWiwhyrOa/JlqXldEIfCn6JpnawpLCv549LbyvUjxX3fUU/w4uDOsMwHNGvyjo5jO0kXb8hFMseBvTrQF5BAp4AoqcPvuF2tsaJGcIqhCIRGQarrio9otAsAYqF5MuzpL3M/XjTRlsrYMt7aZK7Z48RZU6DBH1O5WPMFmr1p1B8wjZLqDsxlxpjW5dmVP+u/r3VAhlCoYunXpIoBRiJEBecNGBtrWvANsLklqOht9wZarNf+2IP9HXRNPmZ3jjYVmYZ+Uef5HjmsLg4/DwykVtgJ1A9dpa1G/C4NXgOFDRnytJY0NbMM/xPvsuu2jvV8py6E69Nr3zV7LHJkKp3c96T5dFRB0Ig==
    SMTP_USER: AQACOOavQWh719Kzasx4T5mo7ziM2AiAq9kjQPvWGJ3BLB9RxmBauhdop7D3xmdU8p3EyghMlzXk4HSryKZU50Nqy2yvuoGj3pfQHaJn/tMb7+63uY05aC5RIS+KcIT+Ag8socFgZTkLP3MJZRevrYzC6Rkakv+iYPxIUOrPd8hlX5aOq5l5abSCiLY7uiqBavmCzWbjhoBsevo8uZnj9NqmjKaexpzp7HAvXNNFTubVxL6MliZ+rTMNhyobZyRRkjlzB7P5vilRCJuvPmXksW8piqxhHLeLZkFOHl5ZIEXuRS2GBbju7vpAgWhTzlEkp7jcJHDwrwuHJiHuvQUi3yPX9tJZVLaBM2rXa1y1G1oRKytEbuR4y5wdcTgz
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: blitz-secrets
      namespace: blitz
