apiVersion: v1
kind: ServiceAccount
metadata:
  name: web3-blitz
  namespace: {{ .Release.Namespace }}
  labels:
    kubepivot.io/name: {{ .Chart.Name }}
    kubepivot.io/instance: {{ .Release.Name }}
    kubepivot.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: kp
