apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: blitz-etcd
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: blitz-etcd
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: blitz
      ports:
        - port: 2379
          protocol: TCP
