// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateDeadLetter(ctx context.Context, arg CreateDeadLetterParams) error
	CreateDeposit(ctx context.Context, arg CreateDepositParams) error
	CreateDepositAddress(ctx context.Context, arg CreateDepositAddressParams) error
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWithdrawal(ctx context.Context, arg CreateWithdrawalParams) (Withdrawal, error)
	GetAddressByAddress(ctx context.Context, address string) (DepositAddress, error)
	GetAllChainsTotalDeposit(ctx context.Context) (interface{}, error)
	GetDepositByTxID(ctx context.Context, txID string) (Deposit, error)
	GetLast24hWithdrawalByUserAndChain(ctx context.Context, arg GetLast24hWithdrawalByUserAndChainParams) (interface{}, error)
	GetRefreshToken(ctx context.Context, token string) (RefreshToken, error)
	GetTotalDepositByChain(ctx context.Context, chain string) (interface{}, error)
	GetTotalDepositByUserIDAndChain(ctx context.Context, arg GetTotalDepositByUserIDAndChainParams) (interface{}, error)
	GetTotalWithdrawalByUserIDAndChain(ctx context.Context, arg GetTotalWithdrawalByUserIDAndChainParams) (interface{}, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserLevel(ctx context.Context, id int64) (int32, error)
	GetWithdrawalLimit(ctx context.Context, level int32) (WithdrawalLimit, error)
	ListAddressesByUserID(ctx context.Context, userID string) ([]DepositAddress, error)
	ListAllDepositAddresses(ctx context.Context) ([]DepositAddress, error)
	ListDepositsByChain(ctx context.Context, chain string) ([]Deposit, error)
	ListDepositsByUserID(ctx context.Context, userID string) ([]Deposit, error)
	ListUnconfirmedDeposits(ctx context.Context) ([]Deposit, error)
	ListUnresolvedDeadLetters(ctx context.Context) ([]DeadLetter, error)
	ListWithdrawalsByUserID(ctx context.Context, userID string) ([]Withdrawal, error)
	ResolveDeadLetter(ctx context.Context, id int64) error
	RevokeAllUserRefreshTokens(ctx context.Context, userID int64) error
	RevokeRefreshToken(ctx context.Context, token string) error
	UpdateDepositConfirmed(ctx context.Context, id int64) error
	UpdateUserLevel(ctx context.Context, arg UpdateUserLevelParams) error
	UpdateWithdrawalTx(ctx context.Context, arg UpdateWithdrawalTxParams) error
}

var _ Querier = (*Queries)(nil)
