// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateDeposit(ctx context.Context, arg CreateDepositParams) error
	CreateDepositAddress(ctx context.Context, arg CreateDepositAddressParams) error
	GetAddressByAddress(ctx context.Context, address string) (DepositAddress, error)
	GetDepositByTxID(ctx context.Context, txID string) (Deposit, error)
	ListAddressesByUserID(ctx context.Context, userID string) ([]DepositAddress, error)
	ListAllDepositAddresses(ctx context.Context) ([]DepositAddress, error)
	ListUnconfirmedDeposits(ctx context.Context) ([]Deposit, error)
}

var _ Querier = (*Queries)(nil)
