// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const createDeposit = `-- name: CreateDeposit :exec
INSERT INTO deposits (tx_id, address, user_id, amount, height, confirmed, chain)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateDepositParams struct {
	TxID      string  `db:"tx_id" json:"tx_id"`
	Address   string  `db:"address" json:"address"`
	UserID    string  `db:"user_id" json:"user_id"`
	Amount    float64 `db:"amount" json:"amount"`
	Height    int64   `db:"height" json:"height"`
	Confirmed int64   `db:"confirmed" json:"confirmed"`
	Chain     string  `db:"chain" json:"chain"`
}

func (q *Queries) CreateDeposit(ctx context.Context, arg CreateDepositParams) error {
	_, err := q.db.ExecContext(ctx, createDeposit,
		arg.TxID,
		arg.Address,
		arg.UserID,
		arg.Amount,
		arg.Height,
		arg.Confirmed,
		arg.Chain,
	)
	return err
}

const createDepositAddress = `-- name: CreateDepositAddress :exec
INSERT OR IGNORE INTO deposit_addresses (user_id, address, chain, path)
VALUES (?, ?, ?, ?)
`

type CreateDepositAddressParams struct {
	UserID  string `db:"user_id" json:"user_id"`
	Address string `db:"address" json:"address"`
	Chain   string `db:"chain" json:"chain"`
	Path    string `db:"path" json:"path"`
}

func (q *Queries) CreateDepositAddress(ctx context.Context, arg CreateDepositAddressParams) error {
	_, err := q.db.ExecContext(ctx, createDepositAddress,
		arg.UserID,
		arg.Address,
		arg.Chain,
		arg.Path,
	)
	return err
}

const getAddressByAddress = `-- name: GetAddressByAddress :one
SELECT id, user_id, address, chain, path, created_at FROM deposit_addresses WHERE address = ? LIMIT 1
`

func (q *Queries) GetAddressByAddress(ctx context.Context, address string) (DepositAddress, error) {
	row := q.db.QueryRowContext(ctx, getAddressByAddress, address)
	var i DepositAddress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Address,
		&i.Chain,
		&i.Path,
		&i.CreatedAt,
	)
	return i, err
}

const getDepositByTxID = `-- name: GetDepositByTxID :one
SELECT id, tx_id, address, user_id, amount, height, confirmed, chain, created_at, updated_at FROM deposits WHERE tx_id = ? LIMIT 1
`

func (q *Queries) GetDepositByTxID(ctx context.Context, txID string) (Deposit, error) {
	row := q.db.QueryRowContext(ctx, getDepositByTxID, txID)
	var i Deposit
	err := row.Scan(
		&i.ID,
		&i.TxID,
		&i.Address,
		&i.UserID,
		&i.Amount,
		&i.Height,
		&i.Confirmed,
		&i.Chain,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAddressesByUserID = `-- name: ListAddressesByUserID :many
SELECT id, user_id, address, chain, path, created_at FROM deposit_addresses WHERE user_id = ? ORDER BY created_at ASC
`

func (q *Queries) ListAddressesByUserID(ctx context.Context, userID string) ([]DepositAddress, error) {
	rows, err := q.db.QueryContext(ctx, listAddressesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DepositAddress
	for rows.Next() {
		var i DepositAddress
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Address,
			&i.Chain,
			&i.Path,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllDepositAddresses = `-- name: ListAllDepositAddresses :many
SELECT id, user_id, address, chain, path, created_at FROM deposit_addresses ORDER BY created_at ASC
`

func (q *Queries) ListAllDepositAddresses(ctx context.Context) ([]DepositAddress, error) {
	rows, err := q.db.QueryContext(ctx, listAllDepositAddresses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DepositAddress
	for rows.Next() {
		var i DepositAddress
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Address,
			&i.Chain,
			&i.Path,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnconfirmedDeposits = `-- name: ListUnconfirmedDeposits :many
SELECT id, tx_id, address, user_id, amount, height, confirmed, chain, created_at, updated_at FROM deposits 
WHERE confirmed = 0 
ORDER BY height ASC
`

func (q *Queries) ListUnconfirmedDeposits(ctx context.Context) ([]Deposit, error) {
	rows, err := q.db.QueryContext(ctx, listUnconfirmedDeposits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deposit
	for rows.Next() {
		var i Deposit
		if err := rows.Scan(
			&i.ID,
			&i.TxID,
			&i.Address,
			&i.UserID,
			&i.Amount,
			&i.Height,
			&i.Confirmed,
			&i.Chain,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
